name: Publish to nuget.org

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_SDK_VERSION: '10.0.x'
  DOTNET_TFM: 'net10.0'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_SDK_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Build .NET Projects
        shell: pwsh
        run: |
          dotnet build --configuration Release

      - name: Run tests
        shell: pwsh
        run: |
          dotnet test --configuration Release --no-restore --verbosity normal

      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach ($file in Get-ChildItem -Recurse -Path . -Filter *.nupkg) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_PUBLISH_TOKEN }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }